### ISSUE TITLE
aboutToAppear中执行this.stateController.loading()无效

### ISSUE THREAD

**Issue by ChinaLike** [ChawLoo/StateLayout#1]
aboutToAppear在build之前执行会造成StateController中的loadingEvent为空，所以无法进行加载框显示，同理其他状态一样

**Comment by ChawLoo** [comment]
这个属于绘制时序问题，aboutToAppear在绘制之前，那自然controller就无法传入，所有的东西也就无法带入了。
axios加载的入参同样有这个时序问题。你有好的建议吗？

**Comment by ChawLoo** [comment]
这个问题我也给官方提过issue，暂时没有得到回复，估计也在讨论中，我自己是采用navigation做路由的，所以在onReady中去触发，没有这个时序问题

**Comment by ChinaLike** [comment]
我在子组件中去调用请求套用navigation感觉也不是很好，时序有问题，是不是考虑@state 状态传递？controller用起来更简洁，看是不是可以配合@State来使用？

**Comment by ChawLoo** [comment]
可以，那我放开原来的方案吧，最初的方案是通过@State去修改的，后来觉得那个太麻烦了,我看看如何优雅的处理

**Comment by ChawLoo** [comment]
1.2.2版本发了，正在审核，审核过了就可以支持手动修改了

**Comment by ChinaLike** [comment]
后期可以慢慢优化，之前方式是优雅点

**Comment by ChawLoo** [comment]
官方回复了，时序问题没办法，不过你可以考虑设置默认初始状态，那不就不需要在aboutToAppear中用Controller处理了吗？或者在aboutToAppear中修改全局的初始缺省状态，一样可以解决问题吧，想象不到有哪些场景是需要在aboutToAPpear中大量修改缺省页的

**Comment by ChinaLike** [comment]
比如说那个Loading，一般在子组件中会在aboutToAPpear获取数据，那就不会显示加载进度

**Comment by ChawLoo** [comment]
> 比如说那个Loading，一般在子组件中会在aboutToAPpear获取数据，那就不会显示加载进度

你可以初始默认缺省页是loading呀，那不是解决问题了？加载结束显示Content

**Comment by ChinaLike** [comment]
想法是很美好，然而里面数据执行很快，即使缺省页面Loading，但是执行完数据有错误也不会显示错误页面，因为这时候build还没有执行完

**Comment by ChinaLike** [comment]
API 12 后 onDidBuild 方法了解没有

**Comment by ChawLoo** [comment]
![image](https://github.com/user-attachments/assets/148188f8-a5b7-4be3-9097-a1835193f8d8)
咋说呢，可以尝试。

**Comment by ChinaLike** [comment]
可以了解一下哇

**Comment by ChawLoo** [comment]
可以，不过这个只是你个人的调用时机，框架不涉及，即使我把框架的 controller赋值方法放到onDidBuild，你在aboutToAppear中调用一样无效的
