### ISSUE TITLE
全局配置希望支持传入builder

### ISSUE THREAD

**Issue by ipad4** [ChawLoo/StateLayout#2]
全局配置希望支持传入builder，当前全局配置的无法满足定制化需求

**Comment by ChawLoo** [comment]
你的组件现在是V1  还是V2

**Comment by ChawLoo** [comment]
已新增，试一下吧，不过全局@Builder特性问题，有一定局限性 @ipad4

**Comment by ChawLoo** [comment]
2.1.0上线了，直接用正式版吧，如果你是V1版本，建议适配V2
